version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  groups:
    all:
      patterns:
      - '*'
  schedule:
    interval: "daily"
- package-ecosystem: "gomod"
  directory: "/internal/tools/"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
