---
apiVersion: rabbitmq.com/v1alpha2
kind: Policy
metadata:
  name: lazy-queue-policy
  namespace: rabbitmq-system
spec:
  name: lazy-queue-policy
  vhost: "test-vhost"
  pattern: "^lazy-queue-" # matches any queue begins with "lazy-queue-"
  applyTo: "queues"
  definition:
    queue-mode: lazy
  rabbitmqClusterReference:
    name: test
---
apiVersion: rabbitmq.com/v1alpha2
kind: Queue
metadata:
  name: lazy-queue-example
  namespace: rabbitmq-system
spec:
  name: lazy-queue-example # matches the pattern "^lazy-queue$" set in lazy-queue-policy
  vhost: "test-vhost"
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: test
