# For more information on lazy queues, see: https://www.rabbitmq.com/lazy-queues.html.
# We recommmend configuring queues through policies to manage them in groups and be able to update queue configurations later on.
---
apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: lazy-queue-policy
spec:
  name: lazy-queue-policy
  vhost: "test-vhost"
  pattern: "^lazy-queue-" # matches any queue begins with "lazy-queue-"
  applyTo: "queues"
  definition:
    queue-mode: lazy
  rabbitmqClusterReference:
    name: test
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: lazy-queue-example
spec:
  name: lazy-queue-example # matches the pattern "^lazy-queue$" set in lazy-queue-policy
  vhost: "test-vhost"
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: test
