# For more information about what/how to configure for quorum queues, see: https://www.rabbitmq.com/quorum-queues.html.
# We recommmend configuring queues through policies to manage them in groups and be able to update queue configurations later on.
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: qq-example
spec:
  name: qq # name of the queue
  vhost: "/test-vhost" # default to '/' if not provided
  type: quorum # without providing a queue type, rabbitmq creates a classic queue
  autoDelete: false
  durable: true # seting 'durable' to false means this queue won't survive a server restart
  rabbitmqClusterReference:
    name: test # rabbitmqCluster must exist in the same namespace as this resource
# status:
#   conditions:
#   - lastTransitionTime: ""
#     status: "True" # true, false, or unknown
#     type: Ready
#     Reason: "SuccessfulCreateOrUpdate" # status false result in reason FailedCreateOrUpdate
#     Message: "" # set when status is false
