apiVersion: rabbitmq.com/v1alpha1
kind: Queue
metadata:
  name: qq-example
  namespace: rabbitmq-system
spec:
  name: test # name of the queue
  vhost: "/test-vhost" # default to '/' if not provided
  rabbitmqClusterReference:
    name: test
    namespace: rabbitmq-system
  type: quorum # without providing a queue type, rabbitmq creates a classic queue
  autoDelete: false
  durable: true
