apiVersion: rabbitmq.com/v1alpha1
kind: User
metadata:
  name: user-sample
  namespace: rabbitmq-system
spec:
  tags:
  - management # available tags are 'management', 'policymaker', 'monitoring' and 'administrator'
  rabbitmqClusterReference:
    name: test
    namespace: rabbitmq-system
# status:
#   conditions:
#   - lastTransitionTime: ""
#     status: "True" # true, false, or unknown
#     type: Ready
#     Reason: "SuccessfulCreateOrUpdate" # status false result in reason FailedCreateOrUpdate
#     Message: "" # set when status is false
