apiVersion: v1
kind: Service
metadata:
  name: messaging-topology-operator-webhook
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app.kubernetes.io/name: messaging-topology-operator
