# permissions for end users to edit operator policies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatorpolicy-editor-role
rules:
- apiGroups:
  - rabbitmq.com
  resources:
  - operatorpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - operatorpolicies/status
  verbs:
  - get
