# permissions for end users to view operator policies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatorpolicy-viewer-role
rules:
- apiGroups:
  - rabbitmq.com
  resources:
  - operatorpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - operatorpolicies/status
  verbs:
  - get
