# permissions for end users to edit shovels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shovel-editor-role
rules:
- apiGroups:
  - rabbitmq.com
  resources:
  - shovels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - shovels/status
  verbs:
  - get
