# permissions for end users to edit topicpermissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topicpermission-editor-role
rules:
- apiGroups:
  - rabbitmq.com
  resources:
  - topicpermissions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - topicpermissions/status
  verbs:
  - get
