# permissions for end users to view vhosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vhost-viewer-role
rules:
- apiGroups:
  - rabbitmq.com
  resources:
  - vhosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - vhosts/status
  verbs:
  - get
