# permissions for end users to edit vhosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vhost-editor-role
rules:
- apiGroups:
  - rabbitmq.com
  resources:
  - vhosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - vhosts/status
  verbs:
  - get
