apiVersion: rabbitmq.com/v1alpha1
kind: Vhost
metadata:
  name: vhost-sample
  namespace: rabbitmq-system
spec:
  name: test-vhost # vhost name
  rabbitmqClusterReference:
    name: test
    namespace: rabbitmq-system
# status:
#   conditions:
#   - lastTransitionTime: ""
#     status: "True" # true, false, or unknown
#     type: Ready
#     Reason: "SuccessfulCreateOrUpdate" # status false result in reason FailedCreateOrUpdate
#     Message: "" # set when status is false
