apiVersion: rabbitmq.com/v1alpha1
kind: Vhost
metadata:
  name: vhost-sample
  namespace: rabbitmq-system
spec:
  name: test-vhost # vhost name
  rabbitmqClusterReference:
    name: test
    namespace: rabbitmq-system
