apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: test-vhost
spec:
  name: test-vhost # vhost name; required and cannot be updated
  defaultQueueType: quorum # default queue type for this vhost; require RabbitMQ version 3.11.12 or above
  rabbitmqClusterReference:
    name: test # rabbitmqCluster must exist in the same namespace as this resource
# status:
#   conditions:
#   - lastTransitionTime: ""
#     status: "True" # true, false, or unknown
#     type: Ready
#     Reason: "SuccessfulCreateOrUpdate" # status false result in reason FailedCreateOrUpdate
#     Message: "" # set when status is false
