apiVersion: rabbitmq.com/v1alpha1
kind: Exchange
metadata:
  name: exchange-example
  namespace: rabbitmq-system
spec:
  name: example # name of the exchange
  vhost: "/test-vhost" # default to '/' if not provided
  rabbitmqClusterReference:
    name: test
    namespace: rabbitmq-system
  type: fanout # default to 'direct' if not provided
  autoDelete: false
  durable: true
# status:
#   conditions:
#   - lastTransitionTime: ""
#     status: "True" # true, false, or unknown
#     type: Ready
#     Reason: "SuccessfulCreateOrUpdate" # status false result in reason FailedCreateOrUpdate
#     Message: "" # set when status is false
