---
apiVersion: rabbitmq.com/v1alpha2
kind: Exchange
metadata:
  name: fanout
  namespace: rabbitmq-system
spec:
  name: fanout-exchange # name of the exchange
  vhost: "/test-vhost" # default to '/' if not provided
  type: fanout # default to 'direct' if not provided
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: test # rabbitmqCluster must exist in the same namespace as this resource
# status:
#   conditions:
#   - lastTransitionTime: ""
#     status: "True" # true, false, or unknown
#     type: Ready
#     Reason: "SuccessfulCreateOrUpdate" # status false result in reason FailedCreateOrUpdate
#     Message: "" # set when status is false
