---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: fanout-upstream
spec:
  name: fanout
  vhost: "upstream" # default to '/' if not provided
  type: fanout # default to 'direct' if not provided
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: example-rabbit
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: fanout-downstream
spec:
  name: fanout
  vhost: "downstream"
  type: fanout
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: example-rabbit
