---
apiVersion: v1
kind: Secret
metadata:
  name: federation-uri
type: Opaque
data:
  uri: #uri to access the 'upstream' vhost; to learn about how to construct a valid uri, see: https://www.rabbitmq.com/uri-spec.html
