---
apiVersion: rabbitmq.com/v1beta1
kind: Federation
metadata:
  name: federation-example
spec:
  name: "origin"
  vhost: "downstream"
  uriSecret:
    name: federation-uri
  ackMode: "on-confirm"
  deletionPolicy: retain # delete or retain; default to delete; require RabbitMQ version xxx or above
  rabbitmqClusterReference:
    name: example-rabbit
