---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: upstream-vhost
spec:
  name: upstream
  rabbitmqClusterReference:
    name: example-rabbit
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: downstream-vhost
spec:
  name: downstream
  rabbitmqClusterReference:
    name: example-rabbit
