---
apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: lazy-queue-policy
spec:
  name: lazy-queue-policy
  vhost: "test-vhost"
  pattern: "^lazy-queue-" # matches any queue begins with "lazy-queue-"
  applyTo: "queues"
  definition:
    queue-mode: lazy
  rabbitmqClusterReference:
    name: sample
