apiVersion: rabbitmq.com/v1alpha1
kind: Policy
metadata:
  name: policy-example
  namespace: rabbitmq-system
spec:
  name: transient # name of the policy
  vhost: "/a-vhost" # default to '/' if not provided
  pattern: "^amq." # regex used to match queues and exchanges
  applyTo: "queues" # set to 'queues', 'exchanges', or 'all'
  definition: # policy definition
    expires: 1800000
  rabbitmqClusterReference:
    name: test
    namespace: rabbitmq-system
