# for more information, see: https://www.rabbitmq.com/shovel-dynamic.html
---
apiVersion: rabbitmq.com/v1beta1
kind: Shovel
metadata:
  name: shovel-example
spec:
  name: "shovel-example"
  uriSecret:
    name: shovel-secret
  srcQueue: "source-queue"
  destQueue: "destination-queue"
  rabbitmqClusterReference:
    name: example-rabbit
