---
apiVersion: v1
kind: Secret
metadata:
  name: shovel-secret
type: Opaque
data:
  destUri: # encoded value for shovel destination URI; to learn about how to construct a valid uri, see: https://www.rabbitmq.com/uri-spec.html
  srcUri: # encoded value shove source URI
